function [w, error_train, error_test] = train_by_epoch(...
    learning, ...
    epoch, ...
    X, ...
    y, ...
    X_test, ...
    y_test, ...
    w)

error_train = zeros(epoch, 1);
error_test = zeros(epoch, 1);

for i = 1:epoch
    w = learning(X, y, w);
    
    error_train(i) = ...
        sum((sign(X * w) - y) .^ 2) / size(X, 1);
    error_test(i) = ...
        sum((sign(X_test * w) - y_test) .^ 2) / size(X_test, 1);
end
